### ISSUE TITLE
Errors with every command

### ISSUE THREAD

**Issue by DanHolli123** [LittleVaaty/VDesk#1]
Every command I try to run gives an output similar to

`Unhandled exception. System.TypeLoadException
   at MS.Win32.Penimc.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   at MS.Win32.Penimc.UnsafeNativeMethods.CreatePimcManager()
   at MS.Win32.Penimc.UnsafeNativeMethods.get_PimcManager()
   at System.Windows.Input.PenThreadWorker.WorkerOperationGetTabletsInfo.OnDoWork()
   at System.Windows.Input.PenThreadWorker.WorkerOperation.DoWork()
   at System.Windows.Input.PenThreadWorker.ThreadProc()
   at System.Threading.Thread.StartCallback()`

This happens both ran with standard user permissions and with admin permission.

I'm using the documented way to enter commands like `vdesk switch 1`

it is worth noting that this doesn't happen when using the `--help` argument

**Comment by DanHolli123** [comment]
It is worth noting that I am on Windows 11 which isn't supported *yet*, but it's worth having in an issue so progress can be tracked

ps: thank you for working on this. Hopefully you can figure it out

**Comment by LittleVaaty** [comment]
i will look into it, but i think is because the actual version of Virtual Desktop is too old.
i everything is good, i will publish a beta for w11 this weekend

**Comment by cruzer619** [comment]
I tested out the latest that was released yesterday.  running standard user permissions get error:

Failure processing application bundle.
Bundle header version compatibility check failed.
A fatal error occured while processing application bundle

when ran as Administrator no errors but when trying to run commands nothing happens..  and I'm running this on Windows11

**Comment by LittleVaaty** [comment]
It seems that is an issues with the single file compilation, i will look into it this afternoon.

**Comment by alexdom** [comment]
Same thing on my side. Thanks for looking into it..

**Comment by LittleVaaty** [comment]
Can you copy/paste the exact errors message. And the build number of windows (you can find it in settings -> System -> About -> OS Build).

**Comment by cruzer619** [comment]
![image](https://github.com/LittleVaaty/VDesk/assets/26581299/f2d57fe3-02ab-400b-8786-0710b4889dcd)
This is my OS build.

**Comment by alexdom** [comment]
My OS:
<img width="627" alt="OS_build" src="https://github.com/LittleVaaty/VDesk/assets/15646314/1af5e91e-1753-465e-b523-a0e022a782b2">

Error:
<img width="211" alt="2023-11-19 00_54_22-VDesk" src="https://github.com/LittleVaaty/VDesk/assets/15646314/a561dcd4-d7dc-4d61-b527-3ecce9feb68a">

**Comment by LittleVaaty** [comment]
The error message seems to be from the old vdesk, did you download it from the release page ? 
https://github.com/LittleVaaty/VDesk/releases

**Comment by alexdom** [comment]
Yeah.. let me try that one. Thanks!

**Comment by alexdom** [comment]
> Yeah.. let me try that one. Thanks!

Looks like the old installed app interfered. Removed it.

**Comment by LittleVaaty** [comment]
OK, i will update the readme to add a better documentation on the install process.

**Comment by cruzer619** [comment]
ok ran the latest released yesterday.   running as standard user getting error:

c:\temp\Downloads\VDesk>vdesk run -o 1 notepad.exe
<3>VDesk.Commands.RunCommand[0] Parameter count mismatch.
        Windows version: 10.0.22621.2134

run as admin: no error but nothing happens.

**Comment by cruzer619** [comment]
![image](https://github.com/LittleVaaty/VDesk/assets/26581299/3fb2a7b5-d914-49e5-ace7-6baf175fbe1e)

Also found a typo in the --help area...  this is the Halloween version.. hahaha

**Comment by LittleVaaty** [comment]
> ok ran beta3. running as standard user getting error:
> 
> C:\temp\Downloads\VDesk>vdesk.exe run -o 1 notepad.exe <3>VDesk.Commands.RunCommand[0] Parameter count mismatch. Windows version: 10.0.22621.2134
> 
> C:\temp\Downloads\VDesk>vdesk.exe run -o 1 notepad.exe -v <6>VDesk.Commands.RunCommand[0] OS Build: 10.0.22621.2134 <6>VDesk.Commands.RunCommand[0] Provider: VDesk.Core.Interop.VirtualDesktopProvider`4[VDesk.Core.Interop.Build22000_0000.IVirtualDesktopManagerInternal,VDesk.Core.Interop.Build22000_0000.IVirtualDesktop,VDesk.Core.Interop.Build22000_0000.IApplicationView,VDesk.Core.Interop.Build22000_0000.IApplicationViewCollection] <3>VDesk.Commands.RunCommand[0] Parameter count mismatch. Windows version: 10.0.22621.2134 System.Reflection.TargetParameterCountException: Parameter count mismatch. at System.Reflection.MethodBaseInvoker.ThrowTargetParameterCountException() at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at VDesk.Core.Interop.ComBaseObject`1.InvokeMethod[T](Object[] parameters, String methodName) at VDesk.Core.Interop.ComObjects.VirtualDesktopManagerInternal`3.GetDesktops()+MoveNext() at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer) at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector) at VDesk.Core.Interop.VirtualDesktopProvider`4.GetDesktop() at VDesk.Commands.RunCommand.Execute(CommandLineApplication app) at VDesk.Commands.VdeskCommandBase.OnExecute(CommandLineApplication app)
> 
> run as admin: no error but nothing happens.

You don't need to launch it as admin. The error is a mismatch between VirtualDesktop and vdesk. Sandly microsoft change it a lot and some update may break vdesk. Since this change are not documented, it a little hard to update correctly vdesk. I will add a way to run vdesk on a specific build but it will be try and error. 
And i need to improve the error message, thats not realy user friendly 😅

**Comment by DanHolli123** [comment]
as both issues of windows 11 compatibility and errors on every command except help have both been resolved, I'm closing this issue
