### ISSUE TITLE
Running: Set correct current working directory (and potentially allow relative path running)

### ISSUE THREAD

**Issue by DoS007** [LittleVaaty/VDesk#10]
VDesk started programs should behave in regard of workings directory like started without vdesk:

# "Normal" Behavior

For testing I have a small `basedir\testdir\test.bat` file which i run in a cmd in `basedir\`contains:

```
@echo off
echo %cd%
echo:
echo %~dp0
echo:
echo %~dpnx0
echo:
echo %~f0
echo:
echo %PATH%
```

This means:

> %cd% refers to the [current working directory](http://en.wikipedia.org/wiki/Working_directory) (variable)
    %~dp0 refers to the full path to the batch file's directory (static)
    %~dpnx0 and %~f0 both refer to the full path to the batch directory and file name (static).

([Source: Stackoverflow](https://stackoverflow.com/a/4420078))

When I run above file in cmd *without* vdesk no matter if i run relative (`.\testdir\test.bat`) or absolute (`"C:\...\basedir\testdir\test.bat"` - exact path not copied here for privacy), I get:

>C:\...\basedir
C:\...\basedir\testdir\
C:\...\basedir\testdir\test.bat
C:\...\basedir\testdir\test.bat
(and the path variable; empty lines not copied)

# Current vdesk behavior
Now starting the batch in the same `basedir\` via vdesk:
`vdesk run -o 1 "C:\...\basedir\testdir\test.bat"` (absolute - exakt path not copied here for privacy).

>C:\...\basedir\testdir
C:\...\basedir\testdir\
C:\...\basedir\testdir\test.bat
C:\...\basedir\testdir\test.bat

Relative running does not work (they all can not find the file):

`vdesk run -o 1 ".\testdir\test.bat"` or

`vdesk run -o 1 .\testdir\test.bat` or

`vdesk run -o 1 "./testdir/test.bat"` or

`vdesk run -o 1 ./testdir/test.bat`

Side note: Didn't list the PATH variable, but they seem to be the same.

# Conclusion
The current working directory differs. So set the ***current working directory correctly***.

This could be important for some programs and i had a problem where this could be the root cause (starting npx on a project).

And not so important: ***Allow relative path running***.

# Importance assessment
The first is important to fix, the second would just be nice but isn't essential.

And as always, thanks for your continuation of vdesk 😊.

**Comment by LittleVaaty** [comment]
Now working directory of the process will be set to the current directory of vdesk.
this also fix relative path.
And i have added your script to my testscript folder.
