### ISSUE TITLE
Not able to run vdesk in windows 11

### ISSUE THREAD

**Issue by cruzer619** [LittleVaaty/VDesk#4]
opening new ticket as there are still issues with vdesk running.

ok ran beta3. running as standard user getting error:

C:\temp\Downloads\VDesk>vdesk.exe run -o 1 notepad.exe <3>VDesk.Commands.RunCommand[0] Parameter count mismatch. Windows version: 10.0.22621.2134

C:\temp\Downloads\VDesk>vdesk.exe run -o 1 notepad.exe -v <6>VDesk.Commands.RunCommand[0] OS Build: 10.0.22621.2134 <6>VDesk.Commands.RunCommand[0] Provider: VDesk.Core.Interop.VirtualDesktopProvider4[VDesk.Core.Interop.Build22000_0000.IVirtualDesktopManagerInternal,VDesk.Core.Interop.Build22000_0000.IVirtualDesktop,VDesk.Core.Interop.Build22000_0000.IApplicationView,VDesk.Core.Interop.Build22000_0000.IApplicationViewCollection] <3>VDesk.Commands.RunCommand[0] Parameter count mismatch. Windows version: 10.0.22621.2134 System.Reflection.TargetParameterCountException: Parameter count mismatch. at System.Reflection.MethodBaseInvoker.ThrowTargetParameterCountException() at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at VDesk.Core.Interop.ComBaseObject1.InvokeMethod[T](Object[] parameters, String methodName) at VDesk.Core.Interop.ComObjects.VirtualDesktopManagerInternal3.GetDesktops()+MoveNext() at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable1 source, Func2 keySelector, Func2 elementSelector, IEqualityComparer1 comparer) at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable1 source, Func2 keySelector, Func2 elementSelector) at VDesk.Core.Interop.VirtualDesktopProvider`4.GetDesktop() at VDesk.Commands.RunCommand.Execute(CommandLineApplication app) at VDesk.Commands.VdeskCommandBase.OnExecute(CommandLineApplication app)

run as admin: no error but nothing happens.

You don't need to launch it as admin. The error is a mismatch between VirtualDesktop and vdesk. Sandly microsoft change it a lot and some update may break vdesk. Since this change are not documented, it's a little hard to update correctly vdesk. I will add a way to run vdesk on a specific build but it will be try and error.
And i need to improve the error message, thats not realy user friendly 😅

**Comment by LittleVaaty** [comment]
Do you still have the issue with the beta 4 ?

**Comment by cruzer619** [comment]
yes still having issue.. but different error:

C:\temp\scripts\VDesk-x64 (1)>vdesk.exe run -o 1 notepad.exe
Failure processing application bundle.
Bundle header version compatibility check failed.
A fatal error occured while processing application bundle

**Comment by LittleVaaty** [comment]
Normaly .net 8 should have fix this issue, i will look into it this weekend

**Comment by LittleVaaty** [comment]
Can you check with the VDesk.exe of the beta 4. (Not the zip one)

**Comment by cruzer619** [comment]
> Can you check with the VDesk.exe of the beta 4. (Not the zip one)

sure thing will try out today

**Comment by cruzer619** [comment]
ok.. that is working.. I'm able to create new desktop.. run app on specific desktop.. nice!!!!

**Comment by cruzer619** [comment]
will test more later on today

**Comment by cruzer619** [comment]
Trying to run this command.  Outlook opens but on the same desktop as I'm running the command on, Desktop 3.

C:\temp\Downloads>VDesk run --no-switch --on 1 "C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.EXE"
<3>VDesk.Commands.RunCommand[0] Element not found. (0x8002802B (TYPE_E_ELEMENTNOTFOUND))
        Windows version: 10.0.22621.3447

**Comment by cruzer619** [comment]
oh and running win11 OS build 22621.3447

**Comment by cruzer619** [comment]
ok did some more testing... looks like the run command works on non-MS Office apps..  Most 3rd party executables i'm able run -no switch .. so thats good..

**Comment by LittleVaaty** [comment]
Ok good, i will close this issue and open a new one for MS App
